language: cpp

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode7.3

matrix:
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  artifacts:
    paths: $(ls powershell*{deb,pkg} | tr "\n" ":")

install:
  - pushd tools
  - ./download.sh
  - popd
  # Default 2.0.0 Ruby is buggy
  # Default bundler version is buggy
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm use 2.2.1; gem uninstall --all bundler; gem install bundler --version '1.12.6'; fi

script: ./tools/travis.sh
